export const levelData = [
  {
    id: 1,
    name: "Bend the Beam",
    description: "Use a mirror to redirect a red laser into the target.",
    grid: [8, 6],
    par: 1,
    sources: [{ x: 0, y: 2, dir: "right", color: "red" }],
    targets: [{ x: 7, y: 5, color: "red" }],
    fixedComponents: [],
    available: [{ type: "mirror", count: 1 }],
  },
  {
    id: 2,
    name: "Paint the Beam",
    description: "Add red to the blue beam so it becomes magenta.",
    grid: [8, 6],
    par: 1,
    sources: [{ x: 0, y: 3, dir: "right", color: "blue" }],
    targets: [{ x: 7, y: 3, color: "magenta" }],
    fixedComponents: [],
    available: [{ type: "filter", color: "red", count: 1 }],
  },
  {
    id: 3,
    name: "Around the Wall",
    description: "A blocker sits in the lane. Detour with two mirrors.",
    grid: [9, 7],
    par: 2,
    sources: [{ x: 0, y: 1, dir: "right", color: "green" }],
    targets: [{ x: 8, y: 4, color: "green" }],
    fixedComponents: [{ x: 5, y: 1, type: "blocker", rotation: 0 }],
    available: [{ type: "mirror", count: 2 }],
  },
  {
    id: 4,
    name: "Split Shot",
    description: "Duplicate one beam to power two red targets.",
    grid: [9, 7],
    par: 1,
    sources: [{ x: 0, y: 3, dir: "right", color: "red" }],
    targets: [
      { x: 8, y: 3, color: "red" },
      { x: 4, y: 6, color: "red" },
    ],
    fixedComponents: [],
    available: [{ type: "splitter", count: 1 }],
  },
  {
    id: 5,
    name: "Two Into One",
    description: "Route red and blue into a combiner to create magenta.",
    grid: [11, 7],
    par: 4,
    sources: [
      { x: 0, y: 2, dir: "right", color: "red" },
      { x: 0, y: 4, dir: "right", color: "blue" },
    ],
    targets: [{ x: 10, y: 3, color: "magenta" }],
    fixedComponents: [],
    available: [
      { type: "mirror", count: 2 },
      { type: "combiner", count: 1, rotation: 1 },
    ],
  },
  {
    id: 6,
    name: "Prism Practice",
    description: "Split a white beam into RGB channels with one prism.",
    grid: [10, 7],
    par: 1,
    sources: [{ x: 0, y: 3, dir: "right", color: "white" }],
    targets: [
      { x: 9, y: 3, color: "red" },
      { x: 3, y: 0, color: "green" },
      { x: 3, y: 6, color: "blue" },
    ],
    fixedComponents: [],
    available: [{ type: "prism", count: 1, rotation: 1 }],
  },
  {
    id: 7,
    name: "Spectrum Lanes",
    description: "Prism plus mirrors: route RGB into three separated targets.",
    grid: [11, 7],
    par: 4,
    sources: [{ x: 0, y: 3, dir: "right", color: "white" }],
    targets: [
      { x: 10, y: 1, color: "green" },
      { x: 10, y: 3, color: "red" },
      { x: 10, y: 5, color: "blue" },
    ],
    fixedComponents: [],
    available: [
      { type: "prism", count: 1, rotation: 1 },
      { type: "mirror", count: 2 },
    ],
  },
  {
    id: 8,
    name: "Grand Circuit",
    description: "Combine red+green into yellow, then split to two targets.",
    grid: [12, 8],
    par: 5,
    sources: [
      { x: 0, y: 2, dir: "right", color: "red" },
      { x: 0, y: 5, dir: "right", color: "green" },
    ],
    targets: [
      { x: 11, y: 4, color: "yellow" },
      { x: 8, y: 1, color: "yellow" },
    ],
    fixedComponents: [],
    available: [
      { type: "mirror", count: 2 },
      { type: "combiner", count: 1, rotation: 1 },
      { type: "splitter", count: 1, rotation: 1 },
    ],
  },
];
